# Generated by Django 4.1.2 on 2022-10-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseinstance',
            name='date',
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
